tunnel: YOUR_TUNNEL_NAME
credentials-file: /home/your-user/.cloudflared/YOUR-TUNNEL-ID.json

ingress:
  - hostname: your-domain.example
    service: http://localhost:80

  - hostname: www.your-domain.example
    service: http://localhost:80

  - hostname: api.your-domain.example
    path: /gateway
    service: http://localhost:4001

  - hostname: api.your-domain.example
    service: http://localhost:3001

  - hostname: cdn.your-domain.example
    service: http://localhost:9000

  - service: http_status:404
